### ISSUE TITLE
remove `unstable` branch

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-taskpools#26]
It seems there is not enough active development in taskpools to motivate the complexity in branch management - ie the branch has gone stale - this would potentially imply renaming `stable` to `main` as usual

**Comment by mratsim** [comment]
There is no unstable branch (unsure who deleted it)

**Comment by arnetheduck** [comment]
https://github.com/status-im/nim-taskpools/tree/unstable - I can see it at least
